version: '3'
services:
  jupyter:
    hostname: jupyter
    container_name: jupyter
    build: .
#    ports:
#      - "5000:80"
    env_file: .env
    volumes:
      - jupyterhome:/home/jupyter
      - ./jupyterprojects:/home/jupyter/projects
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
    networks:
      - proxy_network
networks:
  proxy_network:
    name: proxy_network
    external: true
volumes:
  jupyterhome:
